<ul>
  <li><b>Search for a gene</b> - type the name of a gene or other identifier into the search box above</li>
  <li><b>Find a genome</b> - click in the 'browse a genome' box above and start typing your genome name to find matching genomes</li>
  <li><a href="/species.html">View full list of all Ensembl Bacteria species</a></li>
  <li><a href="http://ensemblgenomes.org/info/access/eg_api">Access Ensembl Bacteria programmatically</a></li>
</ul>
