<h1>Access to over <b>10,000</b> Bacterial Genomes</h1>

<ul>
  <li><b>Search for a gene</b> - type the name of a gene or other identifier into the search box above</li>
  <li><b>Find a genome</b> - click in the 'browse a genome' box above and start typing your genome name to find matching genomes</li>
  <li><a href="/info/about/species.html">View full list of all Ensembl Bacteria species</a></li>
  <li><a href="/info/data/accessing_ensembl_bacteria.html">Access Ensembl Bacteria programmatically</a></li>
</ul>
