<h2 class="title"><img style="float: right;" alt="microme" src="/img/microme.png" height="20" width="104" />Microme Workshop on Microbial Metabolism</h2>
<p><span class="date-display-start">Tuesday, October 8, 2013</span><span class="date-display-separator"> - </span><span class="date-display-end">Thursday, October 10, 2013</span><span class="postal-code">&nbsp;</span> at <a href="https://www.ebi.ac.uk/about/travel">EMBL-EBI</a></p>
<p><span class="postal-code">Registration Deadline: Friday, August 9, 2013<br /></span></p>
<p>Partners from the <a href="http://www.microme.eu/">Microme</a> project will  teach in a number of practical workshop sessions aimed at guiding the  participants through the complexities of networks of metabolites and  biochemical pathways within the current knowledge.</p>
<p>For more details, <a href="http://www.ebi.ac.uk/training/course/bacterial-genomics">click here</a></p>
<h2></h2>