<p>
  Ensembl Bacteria has been developed with the support of the <a href="http://www.microme.eu">Microme</a> project, a resource for bacterial metabolism.
</p>
<p>
  <a href="http://www.microme.eu"><img align="absmiddle" src="img/microme.png" width="104" height="20" alt="" /></a>
  <a style="padding-left:15px" href="http://cordis.europa.eu/fp7/dc/index.cfm"><img align="absmiddle" src="img/eu-fp7.png" width="87" height="30" alt="" title="Seventh Framework Programme (FP7)" /></a>
</p>